In [1]:
import alphazero

model = alphazero.PhilipNet(alphazero.Connect4(), in_channels=3)


import torch

optimizer = torch.optim.Adam(model.parameters())

device = 'cuda:0'

model = alphazero.training.train(alphazero.Connect4,
                                 model,
                                 optimizer,
                                 alphazero.TicTacToeConverter,
                                 n_games=2,
                                 n_mcts_iter=5,
                                 subset_size=2,
                                 temperature=1,
                                 device=device,
                                 )

Playing game 1/2
Playing game 2/2
Self play done, starting training
  [1/2 (50%)]	Loss: 2.768109
  [2/2 (100%)]	Loss: 6.017774
tensor([[-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1., -1.,  1.,  0., -1., -1., -1.],
        [-1.,  1.,  1.,  0., -1., -1., -1.]])
tensor([[-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1., -1.,  1.,  0., -1., -1., -1.],
        [-1.,  1.,  1.,  0., -1., -1., -1.]])
tensor([[-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1., -1.,  1.,  0., -1., -1., -1.],
        [-1.,  1.,  1.,  0., -1., -1., -1.]])
tensor([[-1., -1., -1., -1., -1., -1., -1.],
        [-1., -

In [3]:
model = model.to('cpu')

In [4]:
model = alphazero.training.train(alphazero.Connect4,
                                 model,
                                 optimizer,
                                 alphazero.TicTacToeConverter,
                                 n_games=2,
                                 n_mcts_iter=5,
                                 subset_size=2,
                                 temperature=1,
                                 device=device,
                                 )

Playing game 1/2
Playing game 2/2
Self play done, starting training
  [1/2 (50%)]	Loss: 2.386336
  [2/2 (100%)]	Loss: 5.803688
tensor([[-1., -1., -1.,  1., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1.,  0., -1.,  1., -1., -1., -1.],
        [-1.,  0., -1.,  0., -1., -1., -1.],
        [-1.,  0.,  1.,  1., -1., -1., -1.],
        [-1.,  0.,  1.,  0., -1., -1.,  1.]])
tensor([[-1., -1., -1.,  1., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1.,  0., -1.,  1., -1., -1., -1.],
        [-1.,  0., -1.,  0., -1., -1., -1.],
        [-1.,  0.,  1.,  1., -1., -1., -1.],
        [-1.,  0.,  1.,  0., -1., -1.,  1.]])
tensor([[-1., -1., -1.,  1., -1., -1., -1.],
        [-1., -1., -1.,  0., -1., -1., -1.],
        [-1.,  0., -1.,  1., -1., -1., -1.],
        [-1.,  0., -1.,  0., -1., -1., -1.],
        [-1.,  0.,  1.,  1., -1., -1., -1.],
        [-1.,  0.,  1.,  0., -1., -1.,  1.]])
tensor([[-1., -1., -1.,  1., -1., -1., -1.],
        [-1., -

In [5]:
model = model.to('cpu')